{% set version = "0.10.0" %}

package:
  name: poliastro
  version: {{ version }}

source:
  fn: v{{ version }}.tar.gz
  url: https://github.com/poliastro/poliastro/archive/v{{ version }}.tar.gz
  md5: 7ddd548ce6526dd84549a3e17ee0a507

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  noarch: python

requirements:
  host:
    - python >=3.5
    - setuptools
    - pip

  run:
    - python >=3.5
    - numpy >=1.9
    - scipy
    - numba >=0.25
    - astropy >=2.0.1
    - jplephem
    - matplotlib
    - pandas
    - plotly >=3.0
    - requests
    - beautifulsoup4

test:
  imports:
    - poliastro
    - poliastro.constants
    - poliastro.coordinates
    - poliastro.twobody
    - poliastro.iod
    - poliastro.frames

  requires:
    - pytest

about:
  home: https://poliastro.github.io/
  license: MIT
  summary: "Python package for Orbital Mechanics"

extra:
  recipe-maintainers:
    - juanlu001
