{% set version = "0.7.0" %}

package:
  name: poliastro
  version: {{ version }}

source:
  fn: v{{ version }}.tar.gz
  url: https://github.com/poliastro/poliastro/archive/v{{ version }}.tar.gz
  md5: 601ea71b36999dffa04508cae93e519b

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  skip: True  # [py2k]

requirements:
  build:
    - python
    - setuptools

  run:
    - python >=3.5
    - numpy >=1.9
    - scipy
    - numba >=0.25
    - astropy >=2.0.1
    - jplephem
    - matplotlib
    - pandas
    - requests
    - beautifulsoup4

test:
  imports:
    - poliastro
    - poliastro.constants
    - poliastro.coordinates
    - poliastro.twobody
    - poliastro.iod
    - poliastro.frames

  requires:
    - pytest

about:
  home: https://poliastro.github.io/
  license: MIT
  summary: "Python package for Orbital Mechanics"

extra:
  recipe-maintainers:
    - juanlu001
