{% set version = "0.11.1" %}

package:
  name: poliastro
  version: {{ version }}

source:
  fn: v{{ version }}.tar.gz
  url: https://github.com/poliastro/poliastro/archive/v{{ version }}.tar.gz
  md5: 4ec01dd80854fe5c9ccff803ee31b87b

build:
  number: 1
  script: python -m pip install --no-deps --ignore-installed .
  noarch: python

requirements:
  host:
    - python >=3.5
    - setuptools
    - pip

  run:
    - python >=3.5
    - numpy >=1.9
    - scipy >=1.0
    - numba >=0.39
    - astropy >=3.0,<4
    - jplephem
    - matplotlib
    - pandas
    - plotly >=3.0
    - requests
    - beautifulsoup4

test:
  imports:
    - poliastro
    - poliastro.constants
    - poliastro.coordinates
    - poliastro.twobody
    - poliastro.iod
    - poliastro.frames

  requires:
    - pytest

about:
  home: https://poliastro.github.io/
  license: MIT
  summary: "Python package for Orbital Mechanics"

extra:
  recipe-maintainers:
    - juanlu001
