travis:
  secure:
    BINSTAR_TOKEN: O5fXfBfK/ZEGy5y9FsHj74X+pHXAvRMCJoID7nDHbRdIZitUeoDyYvgMmKl3/ewalzbTkwbl3i9jkJe8ChdWKSFD6aGUI1f1lgpjP5RthURC1E/bFuCkhhPOHw+G5cwnu0JiWFaEjQJZIe0u5a0dzgkFLuQBVOYOVeJKoKADINfPdf/zqNn5EDVffhRF6Q3PYzTA/UxAmEvbgJUfo6BvgNwiHNnAG+kL3EjJJIN4yet/t725y8rEfPSnaiy4nGAvPsKgd6fUW4NGMKLqTGU0gVvnISEwgjyeJyyq4Q97YYuqB1kAZoDEJ5EQKJUf3WgJrPjZLB53CobZ7wtQ37hTD4UsTlDxou7zMPiWRLQmBtTPoRmEdZ+UP4bIqT0m/pyJyEHeJP9AwJUanIYj8OnuWhtiGKeFOyf8tXAK6+tNMKY7vZtzxuyIsxWGN4/47jl7AjUgXowyCLyw0aWx2trxnwn9t+Y34a3ZCaAgeiF+fMBAfgmrSWuoBjLDobZDzfTV3ie5FkRENpbaEHTxdxPTcsDw3JsWWpxdOjnbaTlVQ/EKIctnRjwXJFjPW+tGu6MzaTqnZOqU+Jq9oaQRKFaoiujyejnucocDQvb+VtJFvOfVe7q1pK+cSHT/m5y7BdfsvelywOHknPWAEz3Db7C/BJMynUzCXKT4A0cKSTLXlbw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
